
name: Run Flyway Migrations

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1

jobs:
  flyway-migrate:
    name: Run Flyway Migrations
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Prepare environment variables
      shell: bash
      env:
        PG_HOST: ${{ secrets.PG_DB_HOST }}
        PG_DB: ${{ secrets.PG_DB_NAME }}
        PG_PASSWORD: ${{ secrets.PG_DB_PASSWORD }}
        PG_USER: ${{ secrets.PG_DB_USERNAME }}
        PG_PORT: ${{ secrets.PG_DB_PORT }}
        PG_DB_CERT: ${{ secrets.PG_DB_CERT }}
      run: |
        echo "PG_HOST: $PG_HOST"
        echo "PG_DB: $PG_DB"
        echo "PG_PASSWORD: $PG_PASSWORD"
        echo "PG_USER: $PG_USER"
        echo "PG_PORT: $PG_PORT"
        echo "PG_DB_CERT: $PG_DB_CERT"
    - name: Execute Flyway Migration
      run: |
        docker run --rm \
          -e FLYWAY_URL=jdbc:postgresql://${{ secrets.PG_DB_HOST }}:${{ secrets.PG_DB_PORT }}/${{ secrets.PG_DB_NAME }}?currentSchema=dmsr \
          -e FLYWAY_USER=${{ secrets.PG_DB_USERNAME }} \
          -e FLYWAY_PASSWORD=${{ secrets.PG_DB_PASSWORD }} \
          -v $(pwd)/db:/flyway/sql \
          flyway/flyway:latest migrate
