name: Undo Last Commit

on:
  push:
    branches:
      - main  # or the branch you want

jobs:
  uncommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Undo last commit (soft reset)
        run: |
          git reset --soft HEAD~1
          git status

      - name: Push the changes
        run: |
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
